import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome to my homepage!
        </h1>

        <p className={styles.description}>
          {"I'm Jiho!"}
          <code className={styles.code}>Hi!</code>
        </p>

        <div className={styles.grid}>
          <a href="https://my-first-website-peach.vercel.app/" className={styles.card}>
            <h2>Hello There! &rarr;</h2>
            <p>Visit my first and simple website.</p>
          </a>

          <a href="https://replit.com/~" className={styles.card}>
            <h2>Create &rarr;</h2>
            <p>Search how I made this website!</p>
          </a>

          <a
            href="https://github.com/"
            className={styles.card}
          >
            <h2>Community hub &rarr;</h2>
            <p>Discover Github for yours.</p>
          </a>

          <a
            href="https://vercel.com/dashboard"
            className={styles.card}
          >
            <h2>Launch &rarr;</h2>
            <p>
              Launch your website by vercel!
            </p>
          </a>
          <a href="https://www.youtube.com/channel/UCYe7HWyG-6jTiVDuUyLTyWA" className={styles.card}>
            <h2>Youtube &rarr;</h2>
            <p>Please visit and subscribe my youtube channel!</p>
          </a>
          <a href="https://discord.com/channels/@me" className={styles.card}>
            <h2>Discord &rarr;</h2>
            <p>My ID is Jihourii#4113! Add friend if you want to, or DM me</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.twin-kle.com/users/jihoTheCat"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by JihoTheCat
        </a>
      </footer>
    </div>
  )
}
